name: Optimized Agent

on: workflow_dispatch

jobs:

  build:

    runs-on: windows-2019

    steps:
    - uses: actions/checkout@v3
    
    - name: Login to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USER }}
        password: ${{ secrets.DOCKER_PASSWORD }}
        
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag hasitha2kandy/dockeragent-optimized:latest
      
    - name: Docker Push
      run: docker push hasitha2kandy/dockeragent-optimized:latest
